service: redqueen
provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_REGION}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:*
    Resource: arn:aws:sqs:${env:AWS_REGION}:${env:AWS_ACCOUNTID}:${env:SQS_QUEUE_NAME}
plugins:
  - serverless-dotenv-plugin
functions:
  # hello:
  #   handler: src/handler.hello
  #   events:
  #   - schedule: ${self:custom.globalSchedule}
  #   - http: 
  #       method: get
  #       path: hello
  # cron:
  #   handler: src/cron.default
  #   events:
  #     - schedule: rate(1 minute) 
  # secondCron:
  #   handler: src/secondCron.default
  #   events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      # - schedule: cron(0/2 * ? * MON-FRI *)
  worker:
    handler: src/worker.sendMessagetoSQS
    events:
      - schedule: rate(1 minute) 
      - sqs:
          arn: arn:aws:sqs:${env:AWS_REGION}:${env:AWS_ACCOUNTID}:${env:SQS_QUEUE_NAME}
          batchSize: 1
    description: fetch & get data then send msg to SQS

resources:
  Resources:
    redqueen:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:SQS_QUEUE_NAME}
